app/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
]

app/tg_log_viewer/urls.py
from django.contrib import admin
from django.urls import path, include
import mainapp.views as mainapp

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainapp.main, name='main'),
    path('log/', mainapp.log, name='log'),
    path('log/page/<int:page>/', mainapp.log, name='page'),
    path('search/', mainapp.SearchResultsView.as_view(), name='search'),
    path('peek/<int:pk>/', mainapp.peek, name='peek'),
    path('goto/<int:pk>', mainapp.goto, name='goto'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/mainapp/models.py
import os
from functools import lru_cache
from shutil import copy

from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.search import SearchVectorField, SearchVector
from django.db import models
from django.db.models import Count
from django.utils.translation import gettext_lazy as _

from mainapp.paginator import UserPaginator
from parsers.constants import NOT_DL, OVERSIZE, DL_FOLDER, MAIN_FOLDER
from tg_log_viewer.settings import LOG_MESSAGES_PER_PAGE
from utils.file_hash import hashify_copy


class MessageTypeChoices(models.IntegerChoices):
    TEXT = 0, _("Text")
    GIF = 1, _("Animation")
    STICKER = 2, _("Sticker")
    PHOTO = 3, _("Photo")
    IMAGE_FILE = 4, _("Image file")
    VIDEO = 5, _("Video")
    POLL = 6, _("Poll")
    LOCATION = 7, _("Location")
    ANIMATED_STICKER = 8, _("Animated sticker")
    VOICE_MESSAGE = 9, _("Voice message")
    VIDEO_MESSAGE = 10, _("Video message")
    AUDIO_FILE = 11, _("Audio file")

    OTHER_FILE = 100, _("Other file")


class MediaFile(models.Model):
    is_downloaded = models.BooleanField(verbose_name="media downloaded flag")
    media_type = models.CharField(verbose_name='media_type as in TG log format', max_length=50, null=True, db_index=True)
    mime_type = models.CharField(verbose_name='mime_type as in TG log format', max_length=50, null=True)
    thumbnail = models.CharField(verbose_name='path to a thumbnail bound to this message', max_length=255, blank=True)
    width = models.IntegerField(verbose_name="width of a media file", null=True)
    height = models.IntegerField(verbose_name="height of a media file", null=True)
    duration_seconds = models.IntegerField(verbose_name="duration of a media file", null=True)
    file_path = models.CharField(verbose_name='path to mediafile bound to this message', max_length=255, blank=True)
    sticker_emoji = models.CharField(verbose_name='Emoji for a sticker', max_length=8, null=True)
    performer = models.CharField(verbose_name="Performer tag", max_length=200, null=True)
    title = models.CharField(verbose_name="composition title", max_length=200, null=True)
    hash = models.SlugField(verbose_name="CRC32 hash", max_length=8, null=True)
    size = models.IntegerField(verbose_name="file size", null=True)

    @classmethod
    def create(cls, msg_entry):
        hash_data = None
        if msg_entry.get('media_type') in ('sticker', 'animated_sticker', 'gif'):
            hash_data = hashify_copy(os.path.join(DL_FOLDER, msg_entry['file']))
            file_path = hash_data.get_media_path()
        else:
            file_path = msg_entry['file'] if 'file' in msg_entry else msg_entry['photo']
            copy(os.path.join(DL_FOLDER, file_path),
                 os.path.join(MAIN_FOLDER, file_path))

        media_type = msg_entry.get('media_type')
        if not media_type and msg_entry.get('photo'):
            media_type = 'photo'

        media_data = dict(
            is_downloaded=msg_entry.get('file') != NOT_DL and msg_entry.get('file') != OVERSIZE,
            media_type=media_type,
            mime_type=msg_entry.get('mime_type'),
            thumbnail=msg_entry.get('thumbnail') if msg_entry.get('thumbnail') else "",
            width=msg_entry.get('width'),
            height=msg_entry.get('height'),
            duration_seconds=msg_entry.get('duration_seconds'),
            file_path=file_path,
            sticker_emoji=msg_entry.get('sticker_emoji'),
            performer=msg_entry.get('performer'),
            title=msg_entry.get('title'),
            hash=hash_data.hash if hash_data else None,
            size=hash_data.size if hash_data else None,
        )
        media = cls.objects.create(**media_data)
        return media


class Poll(models.Model):
    question = models.TextField(verbose_name="Poll question")
    closed = models.BooleanField(verbose_name="is a poll closed", default=False)
    total_voters = models.IntegerField(verbose_name="total votes for this poll")

    @classmethod
    def create(cls, poll_data: dict) -> 'Poll':
        answers = poll_data.pop("answers")
        poll = cls.objects.create(**poll_data)

        for answer in answers:
            pa: PollAnswer
            pa = PollAnswer.objects.create(poll=poll, **answer)

        return poll


class PollAnswer(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE, related_name="answers")
    chosen = models.BooleanField(verbose_name="log owner vote for the option", default=False)
    text = models.CharField(verbose_name="option description", max_length=255)
    voters = models.IntegerField(verbose_name="total votes for this option")


class Location(models.Model):
    latitude = models.CharField(verbose_name="Latitude for the location", max_length=20)
    longitude = models.CharField(verbose_name="Longitude for the location", max_length=20)
    place_name = models.CharField(verbose_name="Place name (if available)", max_length=200, null=True)
    address = models.CharField(verbose_name="Location address (if available)", max_length=200, null=True)


class Message(models.Model):

    paginator = UserPaginator

    tg_id = models.PositiveIntegerField(verbose_name="Telegram log id", unique=True)
    date = models.DateTimeField(verbose_name='Message sending time')
    edited = models.DateTimeField(verbose_name='Message edit time', null=True)
    from_name = models.CharField(verbose_name='TG user first name', max_length=100)
    from_id = models.BigIntegerField(verbose_name='TG user ID', null=True)
    content = models.TextField(verbose_name='Message content', blank=True)
    media = models.ForeignKey(MediaFile, on_delete=models.SET_NULL, null=True, related_name="message")
    media_string = models.CharField(blank=True, max_length=100, verbose_name='path to mediafile bound to this message')
    msg_type = models.PositiveIntegerField(verbose_name='message type (related to media type it was carrying', choices=MessageTypeChoices.choices, default=0)
    reply_to_message_id = models.PositiveIntegerField(verbose_name='number of message which this one replies to', default=0)
    forwarded_from = models.CharField(verbose_name='forwarding source', max_length=255, blank=True)
    fwd_time = models.DateTimeField(verbose_name='fwd source sending time', null=True)
    via_bot = models.CharField(verbose_name='inline message sender name', blank=True, max_length=255)
    poll = models.ForeignKey(Poll, verbose_name="A telegram poll results", on_delete=models.SET_NULL, null=True)
    location = models.ForeignKey(Location, on_delete=models.SET_NULL, null=True)

    @property
    def message_page_num(self):
        return (self.pk - 1) // LOG_MESSAGES_PER_PAGE + 1

    @classmethod
    @lru_cache
    def get_distinct_users(cls):
        users_sorted = (
            cls.objects
            .values('from_name')
            .annotate(count=Count('from_name'))
            .order_by('-count')
            .all()
        )

        return users_sorted

    def __str__(self):
        return f'#{self.tg_id} -> {self.from_name} sent this at {self.date}\n' \
               f'{self.content[:50]}\n' \
               f'contains: {self.msg_type} - {self.media}\n' \
               f'is_reply: {self.reply_to_message_id}\n' \
               f'is_fwd: {self.forwarded_from} {self.fwd_time}\n' \
               f'is_inline: {self.via_bot}\n'

    class Meta:
        ordering = ['pk']


class MessageVector(models.Model):
    id = models.AutoField(primary_key=True)
    message = models.ForeignKey(Message, on_delete=models.CASCADE, related_name="vector")
    vector = SearchVectorField(verbose_name="message vectors", null=True)

    class Meta:
        indexes = [
            GinIndex(SearchVector("vector", config='russian'), name="idx_gin_document"),
        ]

app/mainapp/views.py
import re

from django.contrib.postgres.search import SearchQuery
from django.core.paginator import PageNotAnInteger, EmptyPage
from django.shortcuts import render, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import ListView
from tg_log_viewer.settings import LOG_MESSAGES_PER_PAGE

from .models import Message
from .paginator import UserPaginator


# todo should be either prepared in the DB or converted by js on user's side
def message_prepare(message):
    message.content = re.sub(r'\[.*?\]\(https://t\.me/anime_lepra/(\d+)\)', r'<a href="/goto/\1">message#\1</a>', message.content)
    message.content = re.sub(r'\[(.*?)\]\((.*?)\)', r'<a href="\2">🌐\1</a>', message.content)
    message.content = re.sub(r'\n', r'<br>', message.content)


def main(request):
    title = 'something something'

    content = {
        'title': title,
    }

    return render(request, 'mainapp/index.html', context=content)


@login_required
def log(request, page=1):
    title = 'log viewer'

    log_messages = Message.objects.order_by('tg_id')
    user_list = Message.get_distinct_users()

    paginator = UserPaginator(log_messages, LOG_MESSAGES_PER_PAGE)
    try:
        msg_paginator = paginator.page(page)
    except PageNotAnInteger:
        msg_paginator = paginator.page(1)
    except EmptyPage:
        msg_paginator = paginator.page(paginator.num_pages)

    # pprint(msg_paginator)
    # for message in msg_paginator:
    #     message_prepare(message)

    content = {
        'title': title,
        'object_list': msg_paginator,
        'user_list': user_list,
    }
    return render(request, 'mainapp/log.html', context=content)


class SearchResultsView(ListView):
    model = Message
    paginate_by = 500
    template_name = 'mainapp/search.html'

    def get_context_data(self, **kwargs):
        context = super(SearchResultsView, self).get_context_data(**kwargs)
        context['title'] = f"Search: '{self.request.GET.get('query')}'"
        if self.request.GET.get('user'):
            context['title'] += f' ({self.request.GET.get("user")})'
        context['user_list'] = Message.get_distinct_users()
        context['current_user'] = self.request.GET.get('user')
        return context

    def get_queryset(self):
        key = self.request.GET.get('query')
        user = self.request.GET.get('user')
        qs = Message.objects.order_by('tg_id')
        if key != '':
            qs = qs.filter(vector__vector=SearchQuery(key, config='russian'))
        if user != '':
            qs = qs.filter(from_name__iexact=user)
        messages = qs.all()
        return messages

    @method_decorator(login_required())
    def dispatch(self, *args, **kwargs):
        return super(ListView, self).dispatch(*args, **kwargs)

#
# @login_required
# def expand(request, pk=2):
#     title = f'message {pk} in log'
#     BEFORE = 50
#     AFTER = 150
#
#     nearby_messages = Message.objects.filter(id__gte=pk-BEFORE, id__lt=pk+AFTER).order_by('pk')
#     for message in nearby_messages:
#         message_prepare(message)
#
#     content = {
#         'title': title,
#         'object_list': nearby_messages,
#         'highlight': pk,
#     }
#
#     return render(request, 'mainapp/peek.html', context=content)


@login_required
def peek(request, pk):
    title = f'message {pk} in log'
    RANGE = 3

    nearby_messages = Message.objects.filter(tg_id__gte=pk-RANGE, tg_id__lt=pk+RANGE+1).order_by('pk')
    for message in nearby_messages:
        message_prepare(message)

    content = {
        'title': title,
        'object_list': nearby_messages,
        'highlight': pk,
    }

    # print(nearby_messages)

    return render(request, 'mainapp/peek.html', context=content)


@login_required
def goto(request, pk=2):
    title = f'redirecting to message "{pk}" in log...'

    message_to_go = Message.objects.filter(tg_id__gte=pk).order_by('tg_id').first()

    return HttpResponseRedirect(f'/log/page/{message_to_go.message_page_num}#{message_to_go.tg_id}')

app/mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
<!--        <link href="https://fonts.googleapis.com/css?family=Montserrat:100,300,400,500,700&display=swap" rel="stylesheet">-->
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% endblock %}

</head>
<body>
    <div class="container">
        {% block menu %}
            <div class="padding-site topmenu">
                <div class="header clearfix">
                    <h3 class="top-string">{{ title|capfirst }}</h3>
                    <div class="top-string"><a href="{% url 'log' %}">back to main</a></div>
                    <!--        <a class="logo" href="#"><img src="/static/img/logo.svg" alt="logo"></a>-->
                    <form action="{% url 'search' %}" method="get" class="search">
                        <input name="query" type="text" placeholder="Search log..." pattern="[0-9A-Za-zА-Яа-яЁё\s!?.,~`\|\\/#—+_*':@$%()\[\]<>{}-]{3,}">
                        <img @click="toggleExpand" src="/static/img/dropdown.svg" height="20px">
                        <div v-show="expandSearch" class="additional-search">
                            <input name="user" list="userlist" placeholder="Username" value="{% if current_user %}{{ current_user }}{% endif %}">
                            <datalist id="userlist">
                            {% for user in user_list %}
                                <option value="{{user.from_name}}">
                            {% endfor %}
                            </datalist>
                        </div>
                        <input type="submit" value=">>">
                    </form>
                </div>
            </div>
        {% endblock %}

        {% block subtitle %}
        {% endblock %}

        {% block content %}

        {% block messages_list %}
             <div class="messages" id="messages">
            {% for message in object_list %}
                <div class="message-entity {% if message.tg_id == highlight %}highlight{% endif %}" id="{{ message.tg_id }}">
                    <div class="message-header clearfix">
                        <h6 class="message-username">{{ message.from_name }}</h6>
                        {% comment %}<h6 class="message-number"><a href="{% url 'expand' message.tg_id %}#{{ message.tg_id }}">#{{ message.tg_id }}</a></h6>{% endcomment %}
                        <h6 v-if="isSearch" class="message-number" @mouseover="peek($event)" @mouseleave="cleanUp"><a href="{% url 'goto' message.tg_id %}" data-id="{{message.tg_id}}">#{{ message.tg_id }}</a></h6>
                        <h6 v-else class="message-number"><a href="{% url 'goto' message.tg_id %}">#{{ message.tg_id }}</a></h6>
                        <h6 class="message-time">{{ message.date }}</h6>
                        {% if message.reply_to_message_id %}
                            <h6 @mouseover="peek($event)" @mouseleave="cleanUp" class="message-reply-to">
                                <a
                                        href="{% url 'goto' message.reply_to_message_id %}"
                                        data-id="{{message.reply_to_message_id}}"
                                >&gt; {{message.reply_to_message_id}}</a>
                            </h6>
                        {% endif %}
                    </div>
                    <div class="message-content">
                        {% if message.media.media_type == "photo" %}
                            <img class="photo" src="/media/{{ message.media.file_path }}">
                        {% elif message.media.media_type == "sticker" %}
                            <img class="sticker" src="/media/{{ message.media.file_path }}">
                        {% elif message.media.media_type == "animation" %}
                            <video class="gif" src="/media/{{ message.media.file_path }}" loop autoplay></video>
                        {% elif message.media.media_type == "file" %}
                            <a class="file" href="/media/{{ message.media.file_path }}"> 💾 Скачать ({{message.media.file_path}}) </a><br>
                        {% endif %}
                        <p class="message-text">{{ message.content|safe }}</p>
                    </div>
                </div>
            {% endfor %}
            </div>
        {% endblock %}

        {% endblock %}

        <div class="footer padding-site">
            {% block footer %}
            {% endblock %}
        </div>
    </div>

    {% block js %}
<!--        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>-->
<!--        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>-->
<!--        <script src="{% static 'js/bootstrap.min.js' %}"></script>-->
        <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
        <script src="{% static 'js/main.js' %}"></script>
    {% endblock %}

</body>
</html>

app/mainapp/templates/mainapp/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% endblock %}

</head>
<body>
    <div class="container">
        {% block menu %}
            <ul class="menu clearfix">
                <li class="menu-list">
                    {% if user.is_authenticated %}
                        <a href="{% url 'auth:logout' %}" class="menu-link dropdown-item">logout</a>
                    {% else %}
                        <a href="{% url 'auth:login' %}" class="menu-link">login</a>
                    {% endif %}
                </li>
            </ul>
        {% endblock %}

        {% block content %}
        {% endblock %}

        <div class="footer padding-site">
            {% block footer %}
            {% endblock %}
        </div>
    </div>

    {% block js %}
    {% endblock %}
</body>
</html>

app/mainapp/templates/mainapp/log.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block css %}
    {{ block.super }}
{% endblock  %}

{% block menu %}
    {{ block.super }}
{% endblock  %}

{% block subtitle %}
{% endblock %}

{% block content %}
    <div class="logviewer padding-site">
        {% block messages_list %}
            <div class="paginator">
                {% if object_list.has_previous %}
                    <a href="{% url 'page' object_list.previous_page_number %}">&lt;</a>
                {% endif %}
                <span class="current">
                    page {{ object_list.number }} of {{ object_list.paginator.num_pages }}
                </span>
                {% if object_list.has_next %}
                    <a href="{% url 'page' object_list.next_page_number %}">&gt;</a>
                {% endif %}
            </div>

            {{ block.super }}

            <div class="paginator">
                {% if object_list.has_previous %}
                    <a href="{% url 'page' object_list.previous_page_number %}">&lt;</a>
                {% endif %}
                <span class="current">
                    page {{ object_list.number }} of {{ object_list.paginator.num_pages }}
                </span>
                {% if object_list.has_next %}
                    <a href="{% url 'page' object_list.next_page_number %}">&gt;</a>
                {% endif %}
            </div>
        {% endblock %}
    </div>
{% endblock  %}
{% block footer %}
    {{ block.super }}
    <div class="copyright-links">
<!--        <p class="copyright">© Copyright - INTERIOR 2016. All Rights Reserved.</p>-->
    </div>
{% endblock  %}

app/mainapp/templates/mainapp/peek.html
{% for message in object_list %}
    <div class="message-entity {% if message.tg_id == highlight %}highlight{% endif %}">
        <div class="message-header clearfix">
            <h6 class="message-username">{{ message.from_name }}</h6>
            <h6 class="message-number">#{{ message.tg_id }}</h6>
            <h6 class="message-time">{{ message.date }}</h6>
            {% if message.reply_to_message_id %}
                <h6 class="message-reply-to">&gt; {{message.reply_to_message_id}}</h6>
            {% endif %}
        </div>
        <div class="message-content">
            {% if message.media.media_type == "photo" %}
                <img class="photo" src="/media/{{ message.media.file_path }}">
            {% elif message.media.media_type == "sticker" %}
                <img class="sticker" src="/media/{{ message.media.file_path }}">
            {% elif message.media.media_type == "animation" %}
                <video class="gif" src="/media/{{ message.media.file_path }}" loop autoplay></video>
            {% elif message.media.media_type == "file" %}
                <a class="file" href="/media/{{ message.media.file_path }}"> 💾 Скачать ({{message.media.file_path}}) </a><br>
            {% endif %}
            <p class="message-text">{{ message.content|safe }}</p>
        </div>
    </div>
{% endfor %}

app/mainapp/templates/mainapp/search.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block css %}
    {{ block.super }}
{% endblock  %}

{% block menu %}
    {{ block.super }}
{% endblock %}

{% block subtitle %}
    <div class="padding-site subtitle">
        <div class="subheader clearfix">
            <h5>found {{object_list|length}} matches</h5>
    <!--        <a class="logo" href="#"><img src="/static/img/logo.svg" alt="logo"></a>-->
        </div>
    </div>
{% endblock  %}

{% block content %}
<div class="logviewer padding-site">
    {% block messages_list %}
        {{ block.super }}
    {% endblock %}
</div>

{% endblock  %}
{% block footer %}
    {{ block.super }}
    <div class="copyright-links">
<!--        <p class="copyright">© Copyright - INTERIOR 2016. All Rights Reserved.</p>-->
    </div>
{% endblock  %}